# Generated by Django 4.2.7 on 2024-06-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vols_depart_app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.clients')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vols_depart_app.flightdeparture')),
            ],
        ),
    ]
