# Generated by Django 4.2.7 on 2024-06-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('vols_depart_app', '0001_initial'),
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('client', 'flight')},
        ),
    ]
